"""统一交易费率口径。

回测账户、调仓计划和实盘执行器都从这里取费率，避免同一口径散落三份。
"""

COMMISSION_RATE = 0.0000854
MIN_COMMISSION = 0.1
STAMP_TAX_RATE = 0.0005
TRANSFER_FEE_RATE = 0.00002
SIM_SLIPPAGE_RATE = 0

BUY_FEE_RATE = COMMISSION_RATE + TRANSFER_FEE_RATE + SIM_SLIPPAGE_RATE
SELL_FEE_RATE = BUY_FEE_RATE + STAMP_TAX_RATE

LIVE_BUY_FEE_RATE = COMMISSION_RATE + TRANSFER_FEE_RATE
# 实盘买单缺少涨停冻结价时的保守收盘价缓冲。
LIVE_BUY_PRICE_BUFFER = 1.0
